-- MySQL Script generated by MySQL Workbench
-- 06/26/17 18:32:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_sised
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_sised
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sised` DEFAULT CHARACTER SET utf8 ;
USE `db_sised` ;

-- -----------------------------------------------------
-- Table `db_sised`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sised`.`Persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(55) NOT NULL,
  `apellido` VARCHAR(55) NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  `telefono` INT UNSIGNED NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sised`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sised`.`Usuario` (
  `wallet` DECIMAL(7,2) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `puntos` INT NOT NULL,
  `disponible` VARCHAR(45) NOT NULL,
  `Persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`Persona_id_persona`),
  CONSTRAINT `fk_Usuario_Persona1`
    FOREIGN KEY (`Persona_id_persona`)
    REFERENCES `db_sised`.`Persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sised`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sised`.`Cliente` (
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`Persona_id_persona`),
  CONSTRAINT `fk_Cliente_Persona1`
    FOREIGN KEY (`Persona_id_persona`)
    REFERENCES `db_sised`.`Persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sised`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sised`.`Categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sised`.`Trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sised`.`Trabajo` (
  `id_trabajo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio_total` DECIMAL(7,2) NOT NULL,
  `Categoria_id_categoria` INT NOT NULL,
  `Usuario_Persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_trabajo`, `Categoria_id_categoria`, `Usuario_Persona_id_persona`),
  INDEX `fk_Trabajo_Categoria_idx` (`Categoria_id_categoria` ASC),
  INDEX `fk_Trabajo_Usuario1_idx` (`Usuario_Persona_id_persona` ASC),
  CONSTRAINT `fk_Trabajo_Categoria`
    FOREIGN KEY (`Categoria_id_categoria`)
    REFERENCES `db_sised`.`Categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trabajo_Usuario1`
    FOREIGN KEY (`Usuario_Persona_id_persona`)
    REFERENCES `db_sised`.`Usuario` (`Persona_id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sised`.`Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sised`.`Detalle` (
  `id_detalle` INT NOT NULL AUTO_INCREMENT,
  `Trabajo_id_trabajo` INT NOT NULL,
  `Trabajo_Categoria_id_categoria` INT NOT NULL,
  `Cliente_Persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_detalle`, `Trabajo_id_trabajo`, `Trabajo_Categoria_id_categoria`),
  INDEX `fk_Detalle_Trabajo1_idx` (`Trabajo_id_trabajo` ASC, `Trabajo_Categoria_id_categoria` ASC),
  INDEX `fk_Detalle_Cliente1_idx` (`Cliente_Persona_id_persona` ASC),
  CONSTRAINT `fk_Detalle_Trabajo1`
    FOREIGN KEY (`Trabajo_id_trabajo` , `Trabajo_Categoria_id_categoria`)
    REFERENCES `db_sised`.`Trabajo` (`id_trabajo` , `Categoria_id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Cliente1`
    FOREIGN KEY (`Cliente_Persona_id_persona`)
    REFERENCES `db_sised`.`Cliente` (`Persona_id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
